### ISSUE TITLE
Various errors that cause migration to v9 to fail

### ISSUE THREAD

**Issue by YahngSungho** [neutrinojs/neutrino#1350] opened 2019-04-07 20:08 UTC
I used neutrino as the 8.3 version and then tried to migrate to version 9. Despite watching and following the Migration Guide, I encountered various errors.

1)
 `npx @ neutrinojs / migrate` just does not work.
![2019-04-08 04 47 47 untitled  C__Users_Administrator_WebstormProjects_untitled  -  _package json  untitled  - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/55689125-07bc1080-59bc-11e9-96de-cce5d3f67385.png)

So the method I used was to manually modify `.neutrinorc.js` file

2) 
Using the standardjs preset as an example, `standardjs()` as shown in doc does not work.
It seems that an error occurs because `standardjs()` does not have `neutrino` as the first parameter.
![2019-04-08 04 50 23 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _ neutrinorc js  App  - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/55689135-19051d00-59bc-11e9-980f-7002a83e8d6c.png)
![2019-04-08 04 50 38 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _node_modules_@neutrinojs_standardjs_index js - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/55689138-25897580-59bc-11e9-8d46-6b36ebc4d905.png)

So I had to change the `standardjs()` format to `neutrino => (standardjs(neutrino))`.
I don't know if this is the right way. But I just tried to make the error message no longer appear.

3) 
maybe `root: __dirname` does not work(though it's shown in doc)
![2019-04-08 04 45 16 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _node_modules_@neutrinojs_jest_src_index js - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/55689165-59fd3180-59bc-11e9-8a84-f0e5ce4858a8.png)

4) 
`neutrino()` in each config file does not work.
![2019-04-08 04 45 27 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _node_modules_@neutrinojs_jest_src_index js - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/55689144-30dca100-59bc-11e9-84ab-185d15e6e7d6.png)

And it seems that it is not only in `.eslintrc.js`, but also in other files.
![2019-04-08 04 45 37 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _ eslintrc js  App  - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/55689148-39cd7280-59bc-11e9-9c0b-e00a9a4df1ba.png)
![2019-04-08 04 45 50 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _webpack config js  App  - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/55689150-3cc86300-59bc-11e9-9a45-7897e5663617.png)
![2019-04-08 04 46 06 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _jest config js  App  - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/55689153-3f2abd00-59bc-11e9-9015-9fc47b1775ad.png)
![2019-04-08 04 46 12 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _babel config js  App  - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/55689156-4225ad80-59bc-11e9-9a8c-e75ca0dad529.png)

5) 
`import` syntax doesn't work......(maybe)
![2019-04-08 05 31 05 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _ neutrinorc js  App  - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/55689482-e0ffd900-59bf-11e9-919f-928c9668243b.png)
![2019-04-08 05 31 16 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _src_index jsx  App  - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/55689483-e3fac980-59bf-11e9-8df1-80d68f6c3cc9.png)

**Comment by YahngSungho** [comment] 2019-04-07 20:10
This is my .neutrinorc.js

```
const standardjs = require('@neutrinojs/standardjs')
const jest = require('@neutrinojs/jest')
const react = require('@neutrinojs/react')
const emotion = require('neutrino-preset-emotion')
const babelMerge = require('babel-merge')

module.exports = {
  options: {
    mains: {
      index: './index.jsx',
      root: __dirname
    },
  },
  use: [
    // TODO neutrino.use()을 쓴거에대해
    neutrino => {process.env.NODE_ENV === 'development' ? standardjs(neutrino) : false},
    neutrino => {jest(neutrino)},
    neutrino => {react(neutrino, {
        html: {
          title: 'App'
        }
        ,
      targets: {
        browsers: ['last 1 Chrome versions'],
      },
        style: {
          test: /\.(css|sass|scss)$/,
          modulesTest: /\.module\.(css|sass|scss)$/,
          loaders: [
            { loader: require.resolve('sass-loader'), useId: 'sass' },
            {
              loader: 'postcss-loader',
              options: {
                plugins: [require('autoprefixer')]
              }
            },
          ]
        }
      }
    )},
    neutrino => {emotion(neutrino)},
    neutrino => {
      neutrino.config.module
        .rule('compile')
        .use('babel')
        .tap(options => babelMerge({
          plugins: [
            ["@babel/plugin-proposal-decorators", { "legacy": true }],
            ["@babel/plugin-proposal-class-properties", { "loose" : true }]
          ]
        } , options))}
  ]
}
```

**Comment by YahngSungho** [comment] 2019-04-07 20:45
Especially because of 4 and 5, now I can not do anything with neutrino ... Anyone can tell me how to solve them?

**Comment by eliperelman** [comment] 2019-04-11 16:19
Could you share the project or its package.json?

**Comment by YahngSungho** [comment] 2019-04-12 03:22
> Could you share the project or its package.json?

This is my `package.json`

```
{
  "name": "App",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --fix",
    "lint": "eslint --cache --format codeframe --ext mjs,jsx,js src",
    "test": "jest",
    "test:watch": "jest --watch",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook",
    "postinstall": "patch-package"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@blueprintjs/core": "^3.9.0",
    "@types/react": "^16.4.9",
    "@types/react-dom": "^16.0.7",
    "classnames": "^2.2.6",
    "emotion": "^9.2.6",
    "immer": "^1.7.2",
    "katex": "^0.10.0-rc.1",
    "libreact": "^2.8.1",
    "lodash": "^4.17.11",
    "mitt": "^1.1.3",
    "neutrino-preset-decorators": "^0.1.2",
    "neutrino-preset-emotion": "0.0.2",
    "node-sass": "^4.10.0",
    "prop-types": "^15.6.2",
    "proppy": "^1.2.6",
    "proppy-react": "^1.2.6",
    "react": "^16.4.1",
    "react-burger-menu": "^2.5.2",
    "react-chat-ui": "^0.3.2",
    "react-dock": "^0.2.4",
    "react-dom": "^16.4.1",
    "react-emotion": "^9.2.6",
    "react-grid-layout": "^0.16.6",
    "react-hot-loader": "^4.3.3",
    "react-katex": "^2.0.2",
    "react-markdown": "^4.0.2",
    "react-mfb": "^0.6.0",
    "react-mosaic-component": "^2.1.0",
    "react-perf-devtool": "^3.1.8",
    "react-resizable": "^1.7.5",
    "react-scrollbars-custom": "^3.1.5",
    "react-sortable-pane": "^1.0.2",
    "react-sortable-tree": "^2.2.0",
    "react-sortable-tree-theme-file-explorer": "^1.1.2",
    "react-sortable-tree-theme-minimal": "0.0.14",
    "react-sticky": "^6.0.3",
    "react_tree_theme_packaged_yahng_sungho": "^1.17.0",
    "rehype-katex": "^1.1.1",
    "rehype-stringify": "^4.0.0",
    "remark": "^9.0.0",
    "remark-math": "^1.0.4",
    "remark-rehype": "^3.0.1",
    "sass-loader": "^7.1.0",
    "simplebar": "^3.1.1",
    "simplebar-react": "^0.1.1",
    "why-did-you-update": "^1.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-proposal-decorators": "^7.4.0",
    "@babel/preset-env": "^7.4.3",
    "@babel/preset-react": "^7.0.0",
    "@neutrinojs/jest": "^9.0.0-rc.0",
    "@neutrinojs/react": "^9.0.0-rc.0",
    "@neutrinojs/standardjs": "^9.0.0-rc.0",
    "@storybook/addon-actions": "^3.4.8",
    "@storybook/addon-knobs": "^3.4.8",
    "@storybook/addon-links": "^3.4.8",
    "@storybook/addons": "^3.4.8",
    "@storybook/react": "^3.4.8",
    "babel-core": "^7.0.0-bridge.0",
    "babel-loader": "^8.0.5",
    "babel-merge": "^2.0.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-runtime": "^6.26.0",
    "enzyme": "^3.9.0",
    "eslint": "^5.16.0",
    "jest": "^24.7.1",
    "jsdom-quokka-plugin": "^1.0.13",
    "neutrino": "^9.0.0-rc.0",
    "patch-package": "^5.1.1",
    "react-addons-test-utils": "^15.6.2",
    "react-perftool-extension": "^1.0.6",
    "reactotron-react-js": "^2.1.4",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.2.1"
  },
  "quokka": {
    "babel": {
      "presets": [
        "env",
        "react"
      ]
    },
    "plugins": [
      "jsdom-quokka-plugin"
    ]
  }
}
```

**Comment by YahngSungho** [comment] 2019-04-12 04:37
@eliperelman
> Could you share the project or its package.json?

Also my repo is here
https://github.com/YahngSungho/dfsfdsfsfdsfwfsd/tree/helpForNeutrino9

**Comment by eliperelman** [comment] 2019-04-12 15:11
Yeah, it looks like it all comes down to the standardjs package not publishing correctly. Not sure why the `index.js` file didn't publish its latest changes. We will get that resolved in the next release candidate.

**Comment by YahngSungho** [comment] 2019-04-12 15:44
@eliperelman
> Yeah, it looks like it all comes down to the standardjs package not publishing correctly. Not sure why the `index.js` file didn't publish its latest changes. We will get that resolved in the next release candidate.

Thank you for your reply. But are you really sure? There is an uncertain part.

1) The same error occurs in other presets as well as in standardjs. That is, it requires neutrino as the first parameter.

2) The same problem occurred when I installed 9.0 beta version as well as 9.0 rc version.

**Comment by YahngSungho** [comment] 2019-04-13 06:06
@eliperelman
I tried both versions `v9.0.0-beta.1` and ` v9.0.0-beta.0` but all failed with the same problem. What should I do now?

**Comment by edmorley** [comment] 2019-04-13 10:49
So the problem is that the docs on master (https://master.neutrinojs.org/) actually won't work with the latest published pre-release version (9.0.0-rc.0) since there has been a breaking change on master since (#1246). I apologise for the confusion/time this has wasted you!

We hope to release a new release candidate soon, at which point the master docs/setup steps will then work correctly.

**Comment by YahngSungho** [comment] 2019-04-13 17:06
Thank you for your reply.
I understand that presets should not be used as functions in the current release of 9.0, but should be used in the existing string format.

However, even after changing the presets configuration to string, it failed to run 9.0 for a variety of reasons(babel-loader or corejs-related errors). I decided to give up trying 9.0 now. If the next release of 9.0 comes out, I will try again. 
But for other users, how about adding a way to try 9.0 in the current situation to the docs?

**Comment by edmorley** [comment] 2019-04-17 19:19
>  But for other users, how about adding a way to try 9.0 in the current situation to the docs?

v9.0.0-rc.1 has been released, which means the docs on master now match the latest pre-release version. The core-js warning still exists (pending #1366), however it shouldn't stop anything working :-)

**Comment by edmorley** [comment] 2019-04-18 09:13
Reopening since from #1368 it sounds like this still isn't working for you. 

Could you update the testcase repo (https://github.com/YahngSungho/dfsfdsfsfdsfwfsd/tree/helpForNeutrino9) to 9.0.0-rc.1 and I'll take a look?

**Comment by YahngSungho** [comment] 2019-04-18 09:20
@edmorley 

Thank you. I've updated repo
https://github.com/YahngSungho/dfsfdsfsfdsfwfsd/tree/helpForNeutrino9-1

**Comment by YahngSungho** [comment] 2019-04-18 09:24
Also I summarize what I found about what errors occurred after installing 9.0.0-rc.1

1) standardjs still seems not to work
![2019-04-18 17 51 11 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _ eslintrc js  App  - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/56350972-02a26100-6207-11e9-9cee-79ca97cad0d9.png)
There is an error in `.eslintrc.js`. `neutrino()` still does not seem to have  `.eslintrc`.

2) `__dirname` still does not work
![2019-04-18 17 51 45 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _ eslintrc js  App  - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/56351002-1057e680-6207-11e9-87ca-d976b9cdbdca.png)

3) For other presets that are not major, it seems that the function format still does not work.

I wrote
```const neutrinoPresetEmotion = require ('neutrino-preset-emotion');```
To
```
use: [...
neutrinoPresetEmotion (),
...]
```
However, there was an error that the first argument neutrino does not exist.

![2019-04-18 17 53 10 LearnObit  C__Users_Administrator_WebstormProjects_LearnObit  -  _node_modules_neutrino-preset-emotion_index js - WebStorm (Administrator)](https://user-images.githubusercontent.com/29212791/56351028-1d74d580-6207-11e9-9e82-85ede610cd7a.png)

4) When I run npm start, a blank page with nothing is generated. I guess it can't recognize jsx by looking at the console.

![2019-04-18 17 57 44 App - Chrome](https://user-images.githubusercontent.com/29212791/56351032-206fc600-6207-11e9-8b0a-72bda70e2f89.png)

5) I do not know why, but storybook does not run after the update. It says that the command start-storybook does not exist.

![Uploading 2019-04-18 17.59.02 LearnObit [C__Users_Administrator_WebstormProjects_LearnObit] - ..._babel.config.js [App] - WebStorm (Administrator).png…]()

**Comment by edmorley** [comment] 2019-04-18 09:36
Hi! I cloned that repo, checked out the `helpForNeutrino9-1` branch, and ran `yarn` to install the packages.

However both `yarn lint` and `yarn build` work fine for me (they fail, but only because there are formatting corrections that they have found).

Could you try cloning the repo into a clean directory to ensure you're testing what you've given me? (This will also rule out stale `node_modules` and/or broken `package-lock.json`)

Also, when yarn installing there are lots of warnings about invalid peer dependencies - generally these should not be ignored.

Regarding `neutrino-preset-emotion` - this is not an official preset, so will require the author of it to make changes to make it compatible with Neutrino 9. Until they do so it will not work. (It's commented out in the testcase branch though.)

Finally, I would really recommend removing as much of the customisation in `.neutrinorc.js` as possible - most of it is not required as it is already configured in Neutrino's own presets. I see there are also lots of unnecessary packages listed in `package.json` (such as manually installing `@babel/...`) - which only increase the chance of a conflicting package version.

**Comment by YahngSungho** [comment] 2019-04-18 10:41
Thank you for checking my repo.

I generated a new clean folder and cloned a new repo there according to your instructions.
As a result, the problem that the contents in `.eslintrc.js` did not work has been eliminated.
However, there is still a problem with the blank page popping up when running `npm start`. If I check the console, it says messages like `Class constructor Window1 cannot be invoked without 'new'.`
(And `root: __dirname` doesn't work either)

**Closed** 2019-05-28 14:27 UTC

**Comment by edmorley** [comment] 2019-05-31 08:16
Hi! Sorry for not replying to the previous message yet - I've been abroad for a few weeks this month so lots to catch up on. Did you figure out the issue?
