### ISSUE TITLE
Running into npx bug, and npx appears to be a dead project.

### ISSUE THREAD

**Issue by BertusVanZyl** [neutrinojs/neutrino#1466] opened 2019-09-11 06:25 UTC
This is the bug I am experiencing:
https://github.com/zkat/npx/issues/100

Neutrino uses npx to create a new project, but npx does not work.

Also, npx appears to be dead, see this issue: https://github.com/zkat/npx/issues/223

You might consider migrating away from npx for these reasons.

**Comment by edmorley** [comment] 2019-09-11 10:08
Hi! I've personally used Yarn for years and if someone asked me which they should use, would always recommend it over NPM - so I'm not too up to speed on the current npx situation.

Neutrino doesn't use npx per-se - but mentions it as a short-cut in the docs. I agree that if it's no longer reliable we should remove it. However the linked issue only affects one platform and in a particular edge case, and npx still ships with NPM, so until more things appear broken, might be worth still using in the docs? 

We could always list both the npx and npm commands if that helps?

**Comment by edmorley** [comment] 2019-09-11 10:10
In fact the old npx repo now links to https://github.com/npm/npx -- which looks more actively maintained. I would check whether that issue occurs under the new version, and if so, reopen the issue against the new repo to ensure it gets fixed.

**Comment by FrikkinLazer** [comment] 2019-09-11 10:14
If you are aware of the potential risk, and accepted it that is good. Just did not want you to be surprised by your dependencies suddenly becoming unusable, and people following your documentation getting errors (like I did). 

The problem is at first glance it looks like your software is at fault, when its actually npx.

**Comment by edmorley** [comment] 2019-09-11 10:18
Agree totally and I wasn't aware of this bug, so thank you for filing :-)

**Comment by edmorley** [comment] 2019-12-27 16:37
Closing this out for now, since npx appears to still be an active project (and still bundled with node/npm), and whilst this bug does exist, it's (a) somewhat of an edge case so I think not significant enough to mean we don't say to use npx in our docs, (b) something that needs to be fixed upstream, so nothing actionable for us to do (with the docs change ruled out).

Thank you for raising the visibility of the issue and fingers crossed the upstream project fixes it :-)

**Closed by edmorley** 2019-12-27 16:37 UTC
Labels: docs
