### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by Tassfighter** [neutrinojs/neutrino#1409] opened 2019-06-04 08:55 UTC
I have a neutrino react app and a neutrino react component. The react app works without the component. The component works standalone, when started with webpack-dev-server.
But when I integrate the component into the app I got the following error:

> Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app

The problem can be fixed by the following workarounds:
https://reactjs.org/warnings/invalid-hook-call-warning.html

But I wonder if this could be fixed within neutrino, even if it's not directly related to neutrino?

**Comment by edmorley** [comment] 2019-06-09 14:51
Hi! Looking at the react docs linked above, it seems that most of the causes of that error message would be due to invalid project configuration, rather than something cause by Neutrino. Do you have a reduced testcase, so we can see what was configured incorrectly in your project's case, so that we could see if it's viable for Neutrino to check for it and perhaps output a helpful error message?

**Comment by Tassfighter** [comment] 2019-06-11 08:44
See: 
[https://github.com/neutrinojs/neutrino/issues/1406](url)

**Comment by Tassfighter** [comment] 2019-06-14 15:20
My workaround for the time being (webpack.config.js):
```
// Whilst the configuration object can be modified here, the recommended way of making
// changes is via the presets' options or Neutrino's API in `.neutrinorc.js` instead.
// Neutrino's inspect feature can be used to view/export the generated configuration.
const neutrino = require('neutrino');
const path = require('path');

const config = neutrino().webpack();
config.resolve.alias.react = path.resolve('./node_modules/react');
config.resolve.alias["react-redux"] = path.resolve('./node_modules/react-redux');

module.exports = config;
```

**Comment by edmorley** [comment] 2019-09-22 19:51
Sorry for not replying sooner!

So this error message can mean that React got imported multiple times, from different locations on disk - and webpack has ended up requiring it from both of them. 

Looking at the testcase in #1406, I can see this is the case, since there are actually three `node_modules` -- one in the monorepo root, one under `packages/demo_component` and one under `packages/demo_webapp`. 

The [Invalid Hook Call Warning](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react) docs say:

> This problem can also come up when you use npm link or an equivalent.

Lerna does an npm link and doesn't hoist by default:
https://github.com/lerna/lerna/tree/master/commands/bootstrap#--hoist-glob
https://github.com/lerna/lerna/blob/master/doc/hoist.md

I would either start using `--hoist` (to force a single copy of React in the monorepo root `node_modules` or else just use [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) instead (which hoists by default).

It's worth noting that this issue is related to local monorepo development with React rather than something Neutrino-specific. It would not affect end users of `demo_component` if it were published to npmjs, since they wouldn't be using lerna/the monorepo.

Does that help? :-)

**Comment by edmorley** [comment] 2019-09-29 15:36
Closing since this is a limitation of Lerna and the above should resolve the issue. Let us know if it doesn't work :-)

**Closed by edmorley** 2019-09-29 15:36 UTC
Labels: question

**Comment by TylerRick** [comment] 2019-12-06 03:38
I ran into this same error with a `neutrino@9.0.0-rc.5` project using `@neutrinojs/react-components`.

I'm not using lerna, so it's definitely not a problem specific to projects using lerna.

(For that matter, I guess it isn't even specific to projects using neutrino... Seems more like a bug/deficiency with webpack trying to resolve `react` imports within my_component to the `node_modules/` under that library's tree. Maybe someone should create an issue there...)

Whenever I would `yarn link my_component` in my react app, the bundle that the _app's_ webpack produced would end up with 2 copes of `react` and `@material-ui/styles` (which produces a [warning](https://material-ui.com/getting-started/faq/#duplicated-module-in-node-modules) similar to React's), etc. — one from my app and one from `my_component`.

It looks like it actually has more to do with the presence of `node_modules/my_component/node_modules/react` in addition to `node_modules/react`. For some reason I don't understand, webpack resolves some `react` references to one of these and some references to the other, such that both copies of react end up in your bundle.

I found a more minimal way to reproduce this without even using `yarn link`:

```
# Within app dir
ln -s /path/to/my_component/node_modules/react \
  node_modules/my_component/node_modules/react
```

https://reactjs.org/warnings/invalid-hook-call-warning.html even has a warning about this problem:
> This problem can also come up when you use `npm link` or an equivalent. In that case, your bundler might “see” two Reacts — one in application folder and one in your library folder. Assuming `myapp` and `mylib` are sibling folders, one possible fix is to run `npm link ../myapp/node_modules/react` from `mylib`. This should make the library use the application’s React copy.

, though I don't _love_ their suggested workaround. At least there's a workaround though! :)

I arrived at a workaround similar to @Tassfighter's, using `resolve.alias`:

```js
// Make sure dep(s) "A" resolves 'react', etc. ("B" deps) to the exact same copy of react, etc.
// that our app uses so that we don't end up with multiple copies of react, etc. in our bundle
// (which causes warnings/errors).
// This appears to be necessary when using `yarn link` to link to these "A" deps.
config.resolve.alias = [
  'react',
  '@material-ui/styles',
].reduce((hash, dep) => {
  hash[dep] = path.resolve(__dirname, `../../node_modules/${dep}`)
  return hash
}, {})
```


Another workaround is to use reference your local development version of my_component using a [git file URL](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies):
```
 "my_component": "git+file:///path/to/my_component",  
```

This works because the cloned `node_modules/my_component` directory will _not_ end up with any `node_modules` inside of it.
