### ISSUE TITLE
@neutrinojs/library externals cause Karma "Uncaught ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by helfi92** [neutrinojs/neutrino#1251] opened 2018-12-11 14:52 UTC
### Bug

- What version of Neutrino are you using?

`9.0.0-rc.0`

- Are you trying to use any presets? If so, which ones, and what versions?

`@neutrinojs/library@9.0.0-rc.0`
`@neutrinojs/karma@9.0.0-rc.0`

- Are you using the Yarn client or the npm client? What version?

`yarn v1.12.3`

- What version of Node.js are you using?

`10.0.0`

- What operating system are you using?

macOS High Sierra

- What did you do?

Migrate a project from v8 to v9

- What did you expect to happen?

Tests still run

- What actually happened, contrary to your expectations?

`karma start --single-run` throws an error in the terminal

```bash
$ karma start --single-run

START:
ℹ ｢wdm｣: Time: 52ms
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: Time: 667ms
ℹ ｢wdm｣: Compiled successfully.
11 12 2018 09:46:14.553:INFO [karma-server]: Karma v3.1.3 server started at http://0.0.0.0:9876/
11 12 2018 09:46:14.555:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
11 12 2018 09:46:14.562:INFO [launcher]: Starting browser ChromeHeadless
11 12 2018 09:46:14.958:INFO [HeadlessChrome 71.0.3578 (Mac OS X 10.13.4)]: Connected on socket 3u9WFcQb4PFNecstAAAA with id 98496319
HeadlessChrome 71.0.3578 (Mac OS X 10.13.4) ERROR
  {
    "message": "Uncaught ReferenceError: require is not defined\nat test/simple_test.js:930:1\n\nReferenceError: require is not defined\n    at Object.chai (test/simple_test.js:930:1)\n    at __webpack_require__ (test/simple_test.js:30:30)\n    at Module../test/simple_test.js (test/simple_test.js:801:62)\n    at __webpack_require__ (test/simple_test.js:30:30)\n    at test/simple_test.js:94:18\n    at test/simple_test.js:97:10\n    at webpackUniversalModuleDefinition (test/simple_test.js:9:26)\n    at test/simple_test.js:10:3",
    "str": "Uncaught ReferenceError: require is not defined\nat test/simple_test.js:930:1\n\nReferenceError: require is not defined\n    at Object.chai (test/simple_test.js:930:1)\n    at __webpack_require__ (test/simple_test.js:30:30)\n    at Module../test/simple_test.js (test/simple_test.js:801:62)\n    at __webpack_require__ (test/simple_test.js:30:30)\n    at test/simple_test.js:94:18\n    at test/simple_test.js:97:10\n    at webpackUniversalModuleDefinition (test/simple_test.js:9:26)\n    at test/simple_test.js:10:3"
  }
```

**Comment by edmorley** [comment] 2018-12-11 21:53
Could you push the branch that's failing so I can take a look?
Super busy at the moment so a reproducible test case would really help :-)

**Comment by helfi92** [comment] 2018-12-12 01:51
Apologies, I should have sent a test case earlier. https://github.com/taskcluster/taskcluster-client-web/pull/38 :) Thanks in advance.

**Comment by edmorley** [comment] 2018-12-20 15:07
>     1. The solution is to re-add the NODE_ENV conditional inside `@neutrinojs/library` (plus remove the duplicate `externals` call)

Hmm actually, perhaps `@neutrinojs/karma` should be the one that clears out `externals`, since it's the one that needs it? Thoughts?

**Comment by helfi92** [comment] 2018-12-20 16:00
Regarding

```js
    ['@neutrinojs/library', {
      // ...
      babel: {
        presets: [
          [
            require.resolve('@babel/preset-env'),
            {
              debug: false,
              useBuiltIns: 'entry',
              targets: {
                browsers: [
                  'last 2 Chrome versions',
                  'last 2 Firefox versions',
                  'last 2 Edge versions',
                  'last 2 Opera versions',
                  'last 2 Safari versions',
                  'last 2 iOS versions'
                ],
              }
            }
          ]
        ],
      },
    }],
```

This would perform a deepmerge instead of overriding. There will still be a `ie 9` target. I guess we have to override this property from `karma.config.js`.

**Comment by helfi92** [comment] 2018-12-20 16:02
> @neutrinojs/karma should be the one that clears out externals, since it's the one that needs it?

Makes sense to me.

**Comment by edmorley** [comment] 2018-12-20 16:13
> This would perform a deepmerge instead of overriding. There will still be a `ie 9` target. I guess we have to override this property programmatically.

This behaviour didn't occur when I tested locally. 
Note: the merge is performed by babel-merge rather than deepmerge:
https://github.com/neutrinojs/neutrino/blob/448c82c3bb1a144066db27cd7b9ee81c7c7416c8/packages/library/index.js#L33

**Comment by helfi92** [comment] 2018-12-20 16:18
With

```js
['@neutrinojs/library', {
  // ...
  babel: {
    plugins: [
      require.resolve('@babel/plugin-proposal-class-properties'),
    ],
    presets: [
      [
        // TODO: Override using tap() so as to not have to repeat the
        // existing debug/useBuiltIns options. (Or remove entirely if
        // @neutrinojs/library stops defaulting to IE 9 target.)
        require.resolve('@babel/preset-env'),
        {
          debug: false,
          useBuiltIns: 'entry',
          targets: {
            // Override browsers from its default value of 'ie 9'
            browsers: [
              'last 2 Chrome versions',
              'last 2 Firefox versions',
              'last 2 Edge versions',
              'last 2 Opera versions',
              'last 2 Safari versions',
              'last 2 iOS versions'
            ],
          }
        }
      ]
    ],
  },
}],
```

`neutrino --inspect --mode test` shows:

```js
use: [
          /* neutrino.config.module.rule('compile').use('babel') */
          {
            loader: '/Users/haali/Documents/Mozilla/projects/taskcluster-client-web/node_modules/@neutrinojs/compile-loader/node_modules/babel-loader/lib/index.js',
            options: {
              cacheDirectory: true,
              babelrc: false,
              configFile: false,
              presets: [
                [
                  '/Users/haali/Documents/Mozilla/projects/taskcluster-client-web/node_modules/@neutrinojs/library/node_modules/@babel/preset-env/lib/index.js',
                  {
                    debug: false,
                    useBuiltIns: 'entry',
                    targets: {
                      browsers: 'ie 9'
                    }
                  }
                ],
                [
                  '/Users/haali/Documents/Mozilla/projects/node_modules/@babel/preset-env/lib/index.js',
                  {
                    debug: false,
                    useBuiltIns: 'entry',
                    targets: {
                      browsers: [
                        'last 2 Chrome versions',
                        'last 2 Firefox versions',
                        'last 2 Edge versions',
                        'last 2 Opera versions',
                        'last 2 Safari versions',
                        'last 2 iOS versions'
                      ]
                    }
                  }
                ]
              ],
              plugins: [
                '/Users/haali/Documents/Mozilla/projects/taskcluster-client-web/node_modules/@neutrinojs/library/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js',
                '/Users/haali/Documents/Mozilla/projects/taskcluster-client-web/node_modules/@babel/plugin-proposal-class-properties/lib/index.js'
              ]
            }
          }
        ]
```

**Comment by edmorley** [comment] 2018-12-20 16:51
That's not what I get - check for typos? (I also refreshed yarn.lock, try that too?)

```
yarn run v1.13.0
$ C:\Users\Ed\src\taskcluster-client-web\node_modules\.bin\neutrino --inspect
{
  mode: 'development',
  devtool: 'inline-source-map',
  target: 'web',
  context: 'C:\\Users\\Ed\\src\\taskcluster-client-web',
  stats: {
    children: false,
    entrypoints: false,
    modules: false
  },
  node: {
    Buffer: false,
    fs: 'empty',
    tls: 'empty'
  },
  output: {
    path: 'C:\\Users\\Ed\\src\\taskcluster-client-web\\build',
    library: 'taskcluster',
    libraryTarget: 'umd',
    umdNamedDefine: true
  },
  resolve: {
    alias: {
      hawk: 'hawk/dist/browser.js'
    },
    extensions: [
      '.wasm',
      '.mjs',
      '.jsx',
      '.js',
      '.json'
    ]
  },
  module: {
    rules: [
      /* neutrino.config.module.rule('compile') */
      {
        test: /\.(mjs|jsx|js)$/,
        include: [
          'C:\\Users\\Ed\\src\\taskcluster-client-web\\src',
          'C:\\Users\\Ed\\src\\taskcluster-client-web\\test'
        ],
        use: [
          /* neutrino.config.module.rule('compile').use('babel') */
          {
            loader: 'C:\\Users\\Ed\\src\\taskcluster-client-web\\node_modules\\babel-loader\\lib\\index.js',
            options: {
              cacheDirectory: true,
              babelrc: false,
              configFile: false,
              presets: [
                [
                  'C:\\Users\\Ed\\src\\taskcluster-client-web\\node_modules\\@babel\\preset-env\\lib\\index.js',
                  {
                    debug: false,
                    useBuiltIns: 'entry',
                    targets: {
                      browsers: [
                        'last 2 Chrome versions',
                        'last 2 Firefox versions',
                        'last 2 Edge versions',
                        'last 2 Opera versions',
                        'last 2 Safari versions',
                        'last 2 iOS versions'
                      ]
                    }
                  }
                ]
              ],
              plugins: [
                'C:\\Users\\Ed\\src\\taskcluster-client-web\\node_modules\\@babel\\plugin-syntax-dynamic-import\\lib\\index.js',
                'C:\\Users\\Ed\\src\\taskcluster-client-web\\node_modules\\@babel\\plugin-proposal-class-properties\\lib\\index.js'
              ]
            }
          }
        ]
      }
    ]
  },
  entry: {
    index: [
      'C:\\Users\\Ed\\src\\taskcluster-client-web\\src\\index'
    ]
  }
}
Done in 0.30s.
```

**Comment by edmorley** [comment] 2018-12-20 16:52
> `neutrino --inspect --mode test` shows:

This wouldn't have affected the merge, but note that `--mode test` is not a valid mode, and would fail the webpack schema validation if used outside of `--inspect`. Use:
`NODE_ENV=test yarn neutrino --inspect`
(https://master.neutrinojs.org/usage/#inspecting-the-generated-webpack-config)

**Comment by edmorley** [comment] 2018-12-20 17:06
It's because they are in different directories:
`/Users/haali/Documents/Mozilla/projects/node_modules/`
vs
`/Users/haali/Documents/Mozilla/projects/taskcluster-client-web/node_modules/`

I'm presuming due to usage of `NODE_PATH` or similar.

**Comment by edmorley** [comment] 2019-01-12 12:38
I've split the IE9/polyfills part out to #1279, leaving this issue to just be about `@neutrinojs/library` not playing nicely with `@neutrinojs/karma` due to the [externals](https://webpack.js.org/configuration/externals/) option.

There are two ways to fix this (for more context see: https://github.com/neutrinojs/neutrino/issues/1251#issuecomment-449016651):

1. Make `@neutrinojs/library` disable `externals` when `NODE_ENV==='test'`:
2. Make `@neutrinojs/karma` disable `externals` when the `karma` output handler is invoked

Arguments for (1) are:
- It was the way it was implemented in Neutrino 8
- Test frameworks other than Karma don't use webpack at all (they invoke Babel directly), so clearing `externals` is of no consequence to them
- The resultant webpack config is easier to debug, since it's not hiding behaviour under the `karma` output handler (which isn't in the output shown when using `neutrino --inspect`)

Arguments for (2) are:
- All of the other testing presets are for test runners that run under node, so are fine with the `externals` option, so since karma is the one that needs `externals` to not be set, perhaps it should be the one to implement the workaround?

I think I'm leaning towards (1). 

@neutrinojs/core-contributors - thoughts?

**Comment by edmorley** [comment] 2019-02-02 23:17
> I think I'm leaning towards (1).
> @neutrinojs/core-contributors - thoughts?

**Comment by eliperelman** [comment] 2019-03-11 17:16
I think (1) is acceptable. I just pushed a fix for the double `externals` call in the library preset, so I'll get a patch for (1) as well.

**Closed** 2019-03-12 15:00 UTC
Labels: bug
