### ISSUE TITLE
Expand Vue Scaffolding/Tooling

### ISSUE THREAD

**Issue by LFP6** [neutrinojs/neutrino#893] opened 2018-05-20 18:29 UTC
I really appreciate the concept of plugins that Neutrino uses instead of boilerplate (Vue CLI v3 even does this now), however there are some settings upon initial project creation, as well as some Vue-specific tooling, that would be really helpful to have at the get-go (which are included in the [Vue CLI](https://github.com/vuejs/vue-cli), or at least v3)

- Runtime + Compiler or Runtime only
- [Vue Router](https://github.com/vuejs/vue-router)
  - Separate folders for views and components
- [Vuex](https://github.com/vuejs/vuex)
- [ESLint Vue Plugin](https://github.com/vuejs/eslint-plugin-vue)
- Typescript (I know a typescript plugin or two exists elsewhere, but this also includes the core files that are scaffolded, and frankly having official support for TS would be nice)
  - Class-based components
- E2E (Cypress/Nightwatch), though this isn't Vue specific

Even though most of this is scaffolding and not plugins, the point of doing this is less manual up-front setup that wouldn't get changed later anyways (or at least, couldn't be easily/programatically). If its worthwhile to split this into multiple issues, let me know - I didn't want to create a lot of clutter.

**Comment by edmorley** [comment] 2018-05-20 22:00
Hi! Thank you for filing this issue - I've personally never used the Vue preset (and I don't know of many teams at Mozilla that use Vue), so having feedback like this is essential.

I'd definitely be open to updating the create-project template for Vue to use more best practices. 

However now that Vue CLI v3 uses webpack-chain for configuration, I'd be curious to know what use-cases the Neutrino Vue preset fills that the Vue one doesn't? (Both to help work out what our target audience is, and also to sanity-check that we should still keep a Vue preset given that it will likely not get much love from the core Neutrino maintainers, because of their lack of familiarity with Vue.)

**Comment by LFP6** [comment] 2018-05-20 22:48
The benefit for me would be that I work for a project which could presumably use Neutrino as a way to manage boilerplate for testing, ESLint, etc. across multiple projects which use different frameworks. Namely, we're deciding (most likely) between React and Vue for most of our website components, however we have one major component which is being built in PixiJS.

**Comment by edmorley** [comment] 2018-05-21 09:32
Makes sense!

**Comment by LFP6** [comment] 2018-05-31 01:44
@edmorley #158 was closed due to the fact that a community Typescript preset already exists. Would the fact that there is TS-specific scaffolding be sufficient reasoning to include TS as a core module?

I'm debating working on some of these myself if I can properly wrap my head around create-project

**Comment by edmorley** [comment] 2018-06-01 10:32
> @edmorley #158 was closed due to the fact that a community Typescript preset already exists. Would the fact that there is TS-specific scaffolding be sufficient reasoning to include TS as a core module?

@eliperelman thoughts?

**Comment by edmorley** [comment] 2018-08-19 21:34
Re TypeScript definitions, that seems orthogonal - so lets move that discussion to #158.

> when you have the Core contributors of Neutrino taking ownership of those presets the credibility and value of the Core increases, and overall it would make more valuable to use Neutrino knowing that you backed up by the Core maintainers of the package.

The problem is that for some of the lesser-used presets, there are no maintainers for us to even back up/lend a hand to any more. The people who added initial support have not been able to help out with their later maintenance - totally understandable (family/work/other life commitments must come first), but leaves us with lots to cover, and in areas that we don't have first hand experience with. 

I've already personally gone to a lot of effort to try and keep several of these more marginal presets (in terms of relative percentage of Neutrino usage) working when I performed the webpack 4/Babel 7/ESLint 5 upgrades, but in the future we either need to:
1. Find additional maintainers of these lesser used presets
2. Remove support for these presets
3. Accept the fact that major webpack/babel/... upgrades are going to be a bigger pain (due to deps, more moving parts and more things to test), that maintainers like myself (for whom this is a free-time project; I don't really get much official time to work on Neutrino) are going to struggle to justify the time to upgrade webpack/... for the benefit of even the more popular presets like `@neutrinojs/react`

I think for the case of the Vue preset specifically, Evan has done such a great job with Vue CLI 3 ([see write-up here](https://medium.com/the-vue-point/vue-cli-3-0-is-here-c42bebe28fbb)) - that we'd be foolish to invest too much Neutrino core developer time trying to duplicate the awesome UX there, and instead better off focusing on other frameworks/use-cases. If anything I see Vue CLI 3 as an example of how Neutrino has succeeded -- since Vue CLI internally uses [webpack-chain](https://github.com/mozilla-neutrino/webpack-chain) (one of our packages) to manage webpack config, hopefully proving the case for something like https://github.com/webpack/webpack/pull/6395#issuecomment-363762758.

**Comment by yordis** [comment] 2018-08-19 23:16
> The problem is that for some of the lesser-used presets, there are no maintainers for us to even back up/lend a hand to any more. The people who added initial support have not been able to help out with their later maintenance - totally understandable (family/work/other life commitments must come first), but leaves us with lots to cover, and in areas that we don't have first hand experience with.

I totally understand. This is a common issue with this type of projects (I am facing the same issue right now). But sometimes you need to be confident that everything will go as expected.

I should add a comment to what I said because I made too much enfacing on "maintained by the core". Taking ownership of the packages make the folks to concentrate in that package rather than create a new one. It is the "official one".

We like it or not, just by being in the the Neutrino organization the credebility increases and people tend to actually contribute to the packages rather than creating a new one.

Despite if the main package is any good, it doesn't matter, basic human behavior 😃 

That is the good thing of moving into the Org.

Maybe you are not the more qualify to maintain the package and that is fine, just be clear and ask for help on the Github repos, or analyse the implementation and see how long would take you to understand; sometimes is not that bad, for example https://github.com/straw-hat-team/neutrino-graphql/blob/master/src/index.js I am sure you will be able to understand this one.

But my main concern is that you added the `ts` extension but you don't actually support Typescript.

About the Vue topic, I don't see any point on using Neutrino at all for VueJS. Even when Neutrino is an amazing package when it comes to Vue ecosystem there are no benefits of it at all since Vue invested in a robust CLI.

I wouldn't tackle this issue.

But,

I wouldn't say the same on React where the CRA is so locked down that I have to use `react-rewired` for everything. Which is why I am trying to have every single piece of CRA built on Neutrino right now.

It will take me a while because I need to actually remove some of the things you did on `neutrino-react` and `neutrino-web` (maybe) but that is more beneficial for Neutrino project right now.

@LFP6 there is no manual upfront setup with what you mentined since the CLI asked you some questions and create the scaffold for you.

Also worth to mention that the Vue CLI does more than Neutrino is doing. Since Vue UI has some built-in plugin that some of those plugins could implement and Neutrino is not aware of.

So yeah, I wouldn't do anything about it. No worth and you will create another indirection in the ecosystem.

**Comment by yordis** [comment] 2018-08-19 23:18
@edmorley if you close this one, I would like to discuss about Typescript and evaluate with you the solution and what could be the issue from your side.

**Comment by LFP6** [comment] 2018-08-20 00:14
@yordis I'm not sure if it was clear, but my point was that *currently*, these features *would* require manual up-front work with Neutrino since they aren't *yet* included as CLI options.

@edmorley @yordis I completely agree that the v3 Vue CLI UX is great, and trying to put effort into essentially redeveloping that would in general be a waste of time, and also the additional complication in the ecosystem (that is, having two separate packages going after the same thing) would be harmful.

While the original use case still stands (having Vue projects alongside non-Vue projects that should share configuration, though my org hasn't made a final decision yet between React and Vue, if we use React this is a non-issue), I suppose for me personally, it wouldn't be *too much* of a burden to manage our configuration in only two separate places, since in the long run we'll likely only have one non-Vue repo (maybe we could set up our own central configuration repos ie for eslint configs that are interoperable between Neutrino and Vue CLI if we really want to go down that route?).

It would be really nice if it would be possible to have some common ground between the two, so that I could easily use Vue CLI for Vue projects, but rely on the same base configurations as what our Neutrino package(s) use. I have no idea if this is remotely possible, but if anyone has any ideas I'd love to hear them. Is this something that *can* be built into Vue-CLI or Neutrino (providing a compatible format)? Could a new external package be used to more easily provide a Vue-CLI and Neutrino plugin, based around a single configuration? I honestly haven't looked into it and don't know a ton about either ecosystem.

**Comment by yordis** [comment] 2018-08-20 03:50
@LFP6 I understand what you are looking for but at this point, the community has its own niche. As much as I would love Vue CLI be compatible with React and Neutrino and [insert the next CLI here], I don't see that happening right now.

I tried to do exactly what you suggest but it is not worth it.

Use Vue CLI if you are in Vue ecosystem.
Use CRA if you dont want anything custom from React
Use Neutrino if you want to customize CRA and/or create your own setup for the organization.

But looking for a common ground, it will no happen or it will be half good and people would rather use the official ones.

That being said, by all means try to tackle this but it will require a lot of work (I tried to this already and I gave up 😄)

**Comment by eliperelman** [comment] 2018-09-20 18:29
The problem with expanding scaffolding is injecting opinion into the project layout where we have typically remained minimal, which of course is the tradeoff here. Most of the entries in create-project attempt to provide the minimal amount of boilerplate necessary to get started using Neutrino for a particular project type so they can provide a higher value for the many variations those projects can be created.

As such, I'm inclined to say that we should close this. @edmorley thoughts?

**Comment by eliperelman** [comment] 2018-09-20 18:34
Closing for the same reason as #556.

**Closed by eliperelman** 2018-09-20 18:34 UTC
Labels: feature, help wanted
