### ISSUE TITLE
Storybook Storysource Addon Config

### ISSUE THREAD

**Issue by luke-infersens** [neutrinojs/neutrino#1292] opened 2019-02-01 15:20 UTC
Hi All,

I'm trying to add Storybook to an React project.  All working well, and now I'd like to add this addon....

https://github.com/storybooks/storybook/tree/master/addons/storysource#getting-started

Instructions say I need to "use this hook to a custom webpack.config"

`module.exports = function (baseConfig, env, defaultConfig) {
  defaultConfig.module.rules.push({
    test: /\.stories\.jsx?$/,
    loaders: [require.resolve('@storybook/addon-storysource/loader')],
    enforce: 'pre',
  });

  return defaultConfig;
};`

I don't know how that works within Neutrino as I don't have a webpack.config anymore!

Any hints as to where I should be putting this code would be appreciated.

**Comment by edmorley** [comment] 2019-02-02 15:36
Hi! In Neutrino 9 (currently in release-candidate stage), there is now a `webpack.config.js` file, that would make this kind of change easier. For instructions on how to try out the pre-release see #1129.

Good luck! :-)

**Comment by eliperelman** [comment] 2019-03-08 03:21
Closing as duplicate of #1273.

**Closed by eliperelman** 2019-03-08 03:21 UTC
