### ISSUE TITLE
starter project has linting errrors

### ISSUE THREAD

**Issue by MortenHofft** [neutrinojs/neutrino#1249] opened 2018-12-11 14:24 UTC
This is my first experience with Neutrino. It might be on purpose, but there is something frustrating about starting a project that has linting errors before you have even added anything.

It states I might be able to fix it with `npm run lint --fix` but that results in a `npm ERR! code ELIFECYCLE`

This seems to be the same as closed issue https://github.com/neutrinojs/neutrino/issues/608

Thank you for your time

-----

- What version of Neutrino are you using?
 8.3
- Are you using the Yarn client or the npm client? What version?
npm 6.4.1
- What version of Node.js are you using?
10.4.1
- What operating system are you using?
OSX el capitan
- What did you do?
ran the new project command `npx @neutrinojs/create-project somename`
- What did you expect to happen?
a functional project without errors
- What actually happened, contrary to your expectations?
i was asked about my preferences (components, react, jest, airbnb-style)
A project was created. starting the project the linter complains throws errors.

package.json
```
{
  "name": "react-occurrence-search",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "neutrino build",
    "start": "neutrino start",
    "lint": "neutrino lint",
    "test": "neutrino test"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@neutrinojs/airbnb": "^8.3.0",
    "@neutrinojs/jest": "^8.3.0",
    "@neutrinojs/react-components": "^8.3.0",
    "neutrino": "^8.3.0",
    "prop-types": "^15.6.2",
    "react": "^16.6.3",
    "react-dom": "^16.6.3"
  }
}
```

**Comment by edmorley** [comment] 2018-12-11 21:57
Hi! Thank you for filing an issue.

I tried this locally but didn't get an error. Could you paste the full output from the create-project command and also the later `npm run lint --fix`?

**Comment by MortenHofft** [comment] 2018-12-12 19:08
Sure :)
First system
```
Voldemord:test hpotter$ npm --version
6.4.1
Voldemord:test hpotter$ node --version
v10.14.1
```
Now create
```
Voldemord:test hpotter$ npx @neutrinojs/create-project somename
npx: installed 346 in 8.228s
                          _          _
      _ __    ___  _   _ | |_  _ __ (_) _ __    ___
     | '_ \  / _ \| | | || __|| '__|| || '_ \  / _ \
     | | | ||  __/| |_| || |_ | |   | || | | || (_) |
     |_| |_| \___| \__,_| \__||_|   |_||_| |_| \___/
    
Welcome to Neutrino! 👋
To help you create your new project, I am going to ask you a few questions.

? 🤔  First up, what would you like to create? Components
? 🤔  Next, what kind of components would you like to create? React Components
? 🤔  Would you like to add a test runner to your project? Jest
? 🤔  Would you like to add linting to your project? Airbnb style rules

👌  Looks like I have all the info I need. Give me a moment while I create your project!

   create somename/package.json
   create somename/.neutrinorc.js
   create somename/src/components/HelloWorld/index.jsx
   create somename/src/index.jsx
   create somename/test/simple_test.js
   create somename/.eslintrc.js

⏳  Installing devDependencies: @neutrinojs/react-components@^8.3.0, neutrino@^8.3.0, prop-types, react, react-dom, @neutrinojs/jest@^8.3.0, @neutrinojs/airbnb@^8.3.0
⏳  Performing one-time lint

Hooray, I successfully created your project!

I have added a few npm scripts to help you get started:
  • To build your project run:  npm run build
  • To start your project locally run:  npm start
  • To execute tests run:  npm test
  • To lint your project manually run:  npm run lint
    You can also fix some linting problems with:  npm run lint --fix

Now change your directory to the following to get started:
  cd somename

❤️  Neutrino
```

Sounds good. start the project
```
Voldemord:test hpotter$ cd somename/
Voldemord:somename hpotter$ npm start

> somename@1.0.0 start /Users/hpotter/Documents/dev/test/somename
> neutrino start

✔ Development server running on: http://localhost:5000
✔ Build completed

ERROR in ./src/index.jsx
error: Expected a newline after '(' (function-paren-newline) at src/index.jsx:7:7:
   5 | const root = document.getElementById('root');
   6 | 
>  7 | render((
     |       ^
   8 |   <HelloWorld />
   9 | ), root);
  10 | 


error: Expected a newline before ')' (function-paren-newline) at src/index.jsx:9:8:
   7 | render((
   8 |   <HelloWorld />
>  9 | ), root);
     |        ^
  10 | 


2 errors found.
2 errors potentially fixable with the `--fix` option.
 @ multi (webpack)-dev-server/client?http://localhost:5000 (webpack)/hot/dev-server.js ./node_modules/react-hot-loader/patch.js ./src/index

ERROR in ./src/components/HelloWorld/index.jsx
error: Missing trailing comma (comma-dangle) at src/components/HelloWorld/index.jsx:12:25:
  10 | export default class HelloWorld extends PureComponent {
  11 |   static defaultProps = {
> 12 |     initialColor: '#000'
     |                         ^
  13 |   };
  14 | 
  15 |   static propTypes = {


error: Missing trailing comma (comma-dangle) at src/components/HelloWorld/index.jsx:16:25:
  14 | 
  15 |   static propTypes = {
> 16 |     initialColor: string
     |                         ^
  17 |   };
  18 | 
  19 |   state = {


error: Missing trailing comma (comma-dangle) at src/components/HelloWorld/index.jsx:20:35:
  18 | 
  19 |   state = {
> 20 |     color: this.props.initialColor
     |                                   ^
  21 |   };
  22 | 
  23 |   componentWillReceiveProps({ initialColor }) {


error: Missing trailing comma (comma-dangle) at src/components/HelloWorld/index.jsx:31:29:
  29 |   handleClick = () => {
  30 |     this.setState({
> 31 |       color: generateColor()
     |                             ^
  32 |     });
  33 |   };
  34 | 


4 errors found.
4 errors potentially fixable with the `--fix` option.
 @ ./src/index.jsx 4:0-49
 @ multi (webpack)-dev-server/client?http://localhost:5000 (webpack)/hot/dev-server.js ./node_modules/react-hot-loader/patch.js ./src/index
^C
```
run linting
```
Voldemord:somename hpotter$ npm run lint --fix

> somename@1.0.0 lint /Users/hpotter/Documents/dev/test/somename
> neutrino lint

✖ Running lint failed
error: Missing trailing comma (comma-dangle) at src/components/HelloWorld/index.jsx:12:25:
  10 | export default class HelloWorld extends PureComponent {
  11 |   static defaultProps = {
> 12 |     initialColor: '#000'
     |                         ^
  13 |   };
  14 | 
  15 |   static propTypes = {


error: Missing trailing comma (comma-dangle) at src/components/HelloWorld/index.jsx:16:25:
  14 | 
  15 |   static propTypes = {
> 16 |     initialColor: string
     |                         ^
  17 |   };
  18 | 
  19 |   state = {


error: Missing trailing comma (comma-dangle) at src/components/HelloWorld/index.jsx:20:35:
  18 | 
  19 |   state = {
> 20 |     color: this.props.initialColor
     |                                   ^
  21 |   };
  22 | 
  23 |   componentWillReceiveProps({ initialColor }) {


error: Missing trailing comma (comma-dangle) at src/components/HelloWorld/index.jsx:31:29:
  29 |   handleClick = () => {
  30 |     this.setState({
> 31 |       color: generateColor()
     |                             ^
  32 |     });
  33 |   };
  34 | 


error: Expected a newline after '(' (function-paren-newline) at src/index.jsx:7:7:
   5 | const root = document.getElementById('root');
   6 | 
>  7 | render((
     |       ^
   8 |   <HelloWorld />
   9 | ), root);
  10 | 


error: Expected a newline before ')' (function-paren-newline) at src/index.jsx:9:8:
   7 | render((
   8 |   <HelloWorld />
>  9 | ), root);
     |        ^
  10 | 


6 errors found.
6 errors potentially fixable with the `--fix` option.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! somename@1.0.0 lint: `neutrino lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the somename@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hpotter/.npm/_logs/2018-12-12T19_03_16_860Z-debug.log
Voldemord:somename hpotter$ 
```
And as far as I can see the mentioned log file `/Users/hpotter/.npm/_logs/2018-12-12T19_03_16_860Z-debug.log` doesn't give any extra information that could be useful.

Thanks

**Comment by fredmontet** [comment] 2018-12-14 10:41
Just had the same problem with npx (linting error as above). I tried with yarn and the linter didn't produce any error with the boilerplate JS files. (The boilerplate files are different in npx and yarn).

**Comment by edmorley** [comment] 2018-12-19 11:11
Sorry for the delayed reply.

Ah I can now reproduce locally - the reason I could not before, was that it even if I run the create-project command with `npx`, it still finds yarn and uses that instead for the install (I'll file a separate issue for this).

If I pass `--debug` to the create-project command I get:

```
⏳  Installing devDependencies: @neutrinojs/react-components@^8.3.0, neutrino@^8.3.0, prop-types, react, react-dom, @neutrinojs/jest@^8.3.0, @neutrinojs/airbnb@^8.3.0

...

> mozjpeg@4.1.1 postinstall /c/Users/Ed/src/test-project-n8-component/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/c/Users/Ed/src/test-project-n8-component/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/c/Users/Ed/src/test-project-n8-component/node_modules/mozjpeg/vendor" --bindir="/c/Users/Ed/src/test-project-n8-component/node_modules/mozjpeg/vendor" --libdir="/c/Users/Ed/src/test-project-n8-component/node_modules/mozjpeg/vendor" && make --jobs=12 && make install --jobs=12
Command failed: autoreconf -fiv
/bin/sh: 1: autoreconf: not found

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:616:12)

> pngquant-bin@4.0.0 postinstall /c/Users/Ed/src/test-project-n8-component/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/c/Users/Ed/src/test-project-n8-component/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/c/Users/Ed/src/test-project-n8-component/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
npm WARN test-project-n8-component@1.0.0 No description
npm WARN test-project-n8-component@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ed/.npm/_logs/2018-12-19T10_59_05_136Z-debug.log
⏳  Performing one-time lint

Hooray, I successfully created your project!

...
```

So it looks like there were two separate bugs:
1. some of the transient image minification dependencies need additional build tools to run, and fail otherwise (these deps were removed from the web preset in the upcoming Neutrino 9, as part of #815)
2. even though the npm installer exited non-zero, create-project continued regardless when it should have given a clearer error message that the `npm install` had failed (this was fixed in #1079, which is also in the upcoming Neutrino 9)

Could you give the Neutrino 9 release candidate a go, since it should hopefully fix both of these? :-)
 See #1129 for how to use it.

**Comment by edmorley** [comment] 2018-12-19 13:16
> Ah I can now reproduce locally - the reason I could not before, was that it even if I run the create-project command with `npx`, it still finds yarn and uses that instead for the install (I'll file a separate issue for this).

I've filed #1260 for this.

> So it looks like there were two separate bugs:

Make that three, oops!

3. create-project incorrectly runs npm with `npm run lint --fix` rather than `npm run lint -- --fix` which means the fix option never reaches ESLint. This affects Neutrino 8 and 9 when using npm (but not yarn, since it doesn't need the additional `--`). I've filed #1261.

**Comment by edmorley** [comment] 2018-12-19 13:53
I've also filed #1262 for the lint errors not being shown even when passing `--debug` to create-project, and #1263 for making create-project not perform its cleanup when trying to debug these issues.

**Comment by edmorley** [comment] 2018-12-19 14:08
And #1264 for adding CI coverage of npm (currently the create-project test matrix uses yarn throughout).

Until the next Neutrino 9 release that will fix this, the possible workarounds are:
* use yarn with either Neutrino 8 or 9's create-project
* use npm with Neutrino 8's create-project and manually run `npm run lint -- --fix` after the project is created
* use npm with Neutrino 9's create-project and not select a lint preset using the options, and instead add it in manually after by following the docs here: https://master.neutrinojs.org/packages/airbnb/

**Comment by edmorley** [comment] 2019-09-22 15:02
Closing since fixed in Neutrino 9, for which there is a release candidate available (hopefully the final release will be out soon, but the RC is stable enough that I recommend people use it instead of Neutrino 8).

**Closed by edmorley** 2019-09-22 15:02 UTC
Labels: bug, fixed in Neutrino 9
